DROP TABLE IF EXISTS T_PG_FEAR_GREED_INDEX;

CREATE TABLE IF NOT EXISTS T_PG_FEAR_GREED_INDEX AS
SELECT
f.Date_,
f.FG_Value as FG_Index,
f.FG_Textvalue as FG_Value
FROM staging.S_PG_FEAR_GREED_INDEX f
ORDER BY Date_;