#CREATE OR REPLACE TABLE `{{ params.dwh_dataset }}.D_US_YIELDS` AS
SELECT  
  id.DATE as DATE,
  id.NAME_ID as STOCK_ID,
  NULL as COMMODITIES_ID,
  NULL as EXCHANGE_ID
FROM
  `test-344015.TEST_DWH.D_STOCK_PRICE` id
UNION DISTINCT
SELECT 
  DC.DATE as DATE,
  NULL as STOCK_ID,
  DC.NAME_ID as COMMODITIES_ID,
  NULL as EXCHANGE_ID
FROM
  `test-344015.TEST_DWH.D_COMMODITIES` DC
UNION DISTINCT
SELECT 
  DP.DATE as DATE,
  NULL as STOCK_ID,
  NULL as COMMODITIES_ID,
  DP.EXCHANGE_ID as EXCHANGE_ID
FROM
  `test-344015.TEST_DWH.D_EXCHANGE_RATE` DP
ORDER BY DATE ASC

SELECT 
ps.Date as DATE,
ps.Ticker as STOCK_TICKER,
ps.Stock as STOCK_NAME,
ps.Adj_Close as STOCK_PRICE,
si.Industry as STOCK_INDUSTRY,
si.Summary as STOCK_DESCRIPTION,
sf.Total_Liab as TOTAL_LIABILITIES,
sf.Cash as TOTAL_CASH,
sf.Total_Stockholder_Equity

 FROM `test-344015.TEST_DWH_STAGING.PRICE_STAGING` ps 
 LEFT JOIN `test-344015.TEST_DWH_STAGING.STOCK_INFO_STAGING` si 
 ON ps.Ticker = si.Ticker